### ISSUE TITLE
数据标准封包很有意思,有开源协议吗

### ISSUE THREAD

**Issue by yutiansut** [Cuizi7/quotation#1]

**Comment by snowzane** [comment]
@yutiansut 哈哈  @Cuizi7 同学的git主页基本被我刷屏 所以没看见==！

**Comment by yutiansut** [comment]
╭(╯^╰)╮哼唧 我也被你天天刷屏 @wh1100717

**Comment by snowzane** [comment]
😂 😂 😂

**Comment by Cuizi7** [comment]
协议还需要更多讨论，暂时使用Ricequant RQAlpha 中的数据字段对不同的数据源进行封装。
（经过一段时间的更新 RQAlpha 中的数据字段也有变化，这里还需要更新。）
